/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.noel.calculadora;

/**
 *
 * @author noel
 */
public class Calculadora extends javax.swing.JFrame {

    String current_Value;
    String new_Value;
    Double acum = 0.0;
    Double last = 0.0;
    String selected_operation = "";

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jb6 = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jbdot = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jbc = new javax.swing.JButton();
        jbcs = new javax.swing.JButton();
        jbavg = new javax.swing.JButton();
        jbdiv = new javax.swing.JButton();
        jbprod = new javax.swing.JButton();
        jbdif = new javax.swing.JButton();
        jbsum = new javax.swing.JButton();
        jbsqrt = new javax.swing.JButton();
        barra_numeral = new javax.swing.JTextField();
        jbsin = new javax.swing.JButton();
        jbeq2 = new javax.swing.JButton();
        jbpot = new javax.swing.JButton();
        jbcos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb6.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb6.setText("6");
        jb6.setToolTipText("");
        jb6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        jPanel1.add(jb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, 69));

        jb0.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb0.setText("0");
        jb0.setToolTipText("");
        jb0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });
        jPanel1.add(jb0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 160, 69));

        jb1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb1.setText("1");
        jb1.setToolTipText("");
        jb1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });
        jPanel1.add(jb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 80, 69));

        jb2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb2.setText("2");
        jb2.setToolTipText("");
        jb2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        jPanel1.add(jb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 80, 69));

        jb3.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb3.setText("3");
        jb3.setToolTipText("");
        jb3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });
        jPanel1.add(jb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 69));

        jb9.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb9.setText("9");
        jb9.setToolTipText("");
        jb9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });
        jPanel1.add(jb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 80, 69));

        jb5.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb5.setText("5");
        jb5.setToolTipText("");
        jb5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });
        jPanel1.add(jb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 69));

        jb4.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb4.setText("4");
        jb4.setToolTipText("");
        jb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        jPanel1.add(jb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 80, 69));

        jbdot.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbdot.setText(".");
        jbdot.setToolTipText("");
        jbdot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdotActionPerformed(evt);
            }
        });
        jPanel1.add(jbdot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 80, 69));

        jb8.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb8.setText("8");
        jb8.setToolTipText("");
        jb8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        jPanel1.add(jb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 80, 69));

        jb7.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jb7.setText("7");
        jb7.setToolTipText("");
        jb7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });
        jPanel1.add(jb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 80, 69));

        jbc.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbc.setText("C");
        jbc.setToolTipText("");
        jbc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcActionPerformed(evt);
            }
        });
        jPanel1.add(jbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 80, 69));

        jbcs.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbcs.setText("+/-");
        jbcs.setToolTipText("");
        jbcs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcsActionPerformed(evt);
            }
        });
        jPanel1.add(jbcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, 69));

        jbavg.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbavg.setText("%");
        jbavg.setToolTipText("");
        jbavg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbavg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbavgActionPerformed(evt);
            }
        });
        jPanel1.add(jbavg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, 69));

        jbdiv.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbdiv.setText("/");
        jbdiv.setToolTipText("");
        jbdiv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdivActionPerformed(evt);
            }
        });
        jPanel1.add(jbdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 80, 69));

        jbprod.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbprod.setText("x");
        jbprod.setToolTipText("");
        jbprod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprodActionPerformed(evt);
            }
        });
        jPanel1.add(jbprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, 69));

        jbdif.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbdif.setText("-");
        jbdif.setToolTipText("");
        jbdif.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbdif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdifActionPerformed(evt);
            }
        });
        jPanel1.add(jbdif, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 80, 69));

        jbsum.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbsum.setText("+");
        jbsum.setToolTipText("");
        jbsum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsumActionPerformed(evt);
            }
        });
        jPanel1.add(jbsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 80, 69));

        jbsqrt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jbsqrt.setText("sqrt()");
        jbsqrt.setToolTipText("");
        jbsqrt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsqrtActionPerformed(evt);
            }
        });
        jPanel1.add(jbsqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 80, 69));

        barra_numeral.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        barra_numeral.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        barra_numeral.setAlignmentX(30.0F);
        barra_numeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_numeralActionPerformed(evt);
            }
        });
        jPanel1.add(barra_numeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 60));

        jbsin.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbsin.setText("sin");
        jbsin.setToolTipText("");
        jbsin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsinActionPerformed(evt);
            }
        });
        jPanel1.add(jbsin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 80, 69));

        jbeq2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbeq2.setText("=");
        jbeq2.setToolTipText("");
        jbeq2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbeq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeq2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbeq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 80, 69));

        jbpot.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbpot.setText("^2");
        jbpot.setToolTipText("");
        jbpot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbpot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpotActionPerformed(evt);
            }
        });
        jPanel1.add(jbpot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 80, 69));

        jbcos.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jbcos.setText("cos");
        jbcos.setToolTipText("");
        jbcos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcosActionPerformed(evt);
            }
        });
        jPanel1.add(jbcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 80, 69));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        // TODO add your handling code here:
        current_Value = barra_numeral.getText();
        new_Value = current_Value + "6";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
          current_Value = barra_numeral.getText();
        new_Value = current_Value + "0";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb0ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
              current_Value = barra_numeral.getText();
        new_Value = current_Value + "1";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
              current_Value = barra_numeral.getText();
        new_Value = current_Value + "2";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
             current_Value = barra_numeral.getText();
        new_Value = current_Value + "3";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb3ActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
            current_Value = barra_numeral.getText();
        new_Value = current_Value + "9";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
          current_Value = barra_numeral.getText();
        new_Value = current_Value + "5";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb5ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        // TODO add your handling code here:
             current_Value = barra_numeral.getText();
        new_Value = current_Value + "4";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb4ActionPerformed

    private void jbdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdotActionPerformed
        // TODO add your handling code here:
        current_Value = barra_numeral.getText();
        new_Value = current_Value + ".";
        barra_numeral.setText(new_Value);
    }//GEN-LAST:event_jbdotActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        // TODO add your handling code here:
              current_Value = barra_numeral.getText();
        new_Value = current_Value + "8";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        // TODO add your handling code here:
              current_Value = barra_numeral.getText();
        new_Value = current_Value + "7";
        barra_numeral.setText(new_Value);
        if (selected_operation.equals("suma")) {
            acum = acum + Double.valueOf(new_Value);
        } else if (selected_operation.equals("resta")) {
            acum = acum - last;
            acum = last - Double.valueOf(new_Value);
        } else if (selected_operation.equals("prod")) {
            acum = last * Double.valueOf(new_Value);
        }
         else if (selected_operation.equals("div")) {
            acum = last / Double.valueOf(new_Value);
        }
    }//GEN-LAST:event_jb7ActionPerformed

    private void jbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcActionPerformed
        // TODO add your handling code here:
        current_Value = "";
        new_Value = "";
        acum = 0.0;
        last = 0.0;
        selected_operation = "";
        barra_numeral.setText(new_Value);
    }//GEN-LAST:event_jbcActionPerformed

    private void jbcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcsActionPerformed
        // TODO add your handling code here:
         current_Value = barra_numeral.getText();
         
         if(current_Value.contains("-")){
              barra_numeral.setText(current_Value.replace("-", "+"));
         }else if(current_Value.contains("+")){
               barra_numeral.setText(current_Value.replace("+", "-"));
         }else{
               barra_numeral.setText("+"+current_Value);
         }
         
    }//GEN-LAST:event_jbcsActionPerformed

    private void jbavgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbavgActionPerformed
        // TODO add your handling code here:
        current_Value = barra_numeral.getText();
        Double writen_num = Double.valueOf(current_Value);
        Double res = writen_num / 100;
        new_Value = res + "";
        barra_numeral.setText(new_Value);
    }//GEN-LAST:event_jbavgActionPerformed

    private void jbdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdivActionPerformed
        // TODO add your handling code here:
           selected_operation = "div";
        last = Double.valueOf(barra_numeral.getText());
        barra_numeral.setText("");
    }//GEN-LAST:event_jbdivActionPerformed

    private void jbprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprodActionPerformed
        // TODO add your handling code here:
        selected_operation = "prod";
        last = Double.valueOf(barra_numeral.getText());
        barra_numeral.setText("");
    }//GEN-LAST:event_jbprodActionPerformed

    private void jbdifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdifActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        selected_operation = "resta";
        last = Double.valueOf(barra_numeral.getText());
        barra_numeral.setText("");
    }//GEN-LAST:event_jbdifActionPerformed

    private void jbsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsumActionPerformed
        // TODO add your handling code here:
        selected_operation = "suma";
        last = Double.valueOf(barra_numeral.getText());
        barra_numeral.setText("");
    }//GEN-LAST:event_jbsumActionPerformed

    private void jbsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsqrtActionPerformed
        // TODO add your handling code here:
        current_Value=barra_numeral.getText();
        last = 0.0;
        acum=Math.sqrt(Double.parseDouble(current_Value));
        selected_operation = "";
        barra_numeral.setText(""+ acum);
    }//GEN-LAST:event_jbsqrtActionPerformed

    private void barra_numeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_numeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_numeralActionPerformed

    private void jbsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsinActionPerformed
        // TODO add your handling code here:
                       current_Value=barra_numeral.getText();
        last = 0.0;
        acum=Math.sin(Double.parseDouble(current_Value));
        selected_operation = "";
        barra_numeral.setText(""+ acum);
    }//GEN-LAST:event_jbsinActionPerformed

    private void jbeq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeq2ActionPerformed
        // TODO add your handling code here:
        barra_numeral.setText(acum + "");
        last = 0.0;
        selected_operation = "";
        System.out.print(acum + "a3\n");
        System.out.print(last + "l3\n");
    }//GEN-LAST:event_jbeq2ActionPerformed

    private void jbpotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpotActionPerformed
        // TODO add your handling code here:
                current_Value=barra_numeral.getText();
        last = 0.0;
        acum=Math.pow(Double.parseDouble(current_Value), 2);
        selected_operation = "";
        barra_numeral.setText(""+ acum);
    }//GEN-LAST:event_jbpotActionPerformed

    private void jbcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcosActionPerformed
        // TODO add your handling code here:
           current_Value=barra_numeral.getText();
        last = 0.0;
        acum=Math.cos(Double.parseDouble(current_Value));
        selected_operation = "";
        barra_numeral.setText(""+ acum);
    }//GEN-LAST:event_jbcosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barra_numeral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbavg;
    private javax.swing.JButton jbc;
    private javax.swing.JButton jbcos;
    private javax.swing.JButton jbcs;
    private javax.swing.JButton jbdif;
    private javax.swing.JButton jbdiv;
    private javax.swing.JButton jbdot;
    private javax.swing.JButton jbeq2;
    private javax.swing.JButton jbpot;
    private javax.swing.JButton jbprod;
    private javax.swing.JButton jbsin;
    private javax.swing.JButton jbsqrt;
    private javax.swing.JButton jbsum;
    // End of variables declaration//GEN-END:variables
}
